import { ClientProfile, TaskItem, TeamMemberCapacity } from "./types";

export const INITIAL_CLIENTS: ClientProfile[] = [
  {
    id: "oswal",
    name: "Oswal Exports",
    code: "C-01",
    entityType: "Partnership Firm",
    industry: "Handicraft Export",
    turnover: "₹3.8 Cr",
    tier: 1,
    health: "at-risk",
    pan: "AAAFO1234F",
    tan: "MUMB12345C",
    udyam: "UDYAM-MH-01-0049281",
    gstins: [
      { state: "Maharashtra (27)", gstin: "27AAAFO1234F1Z5" },
      { state: "Gujarat (24)", gstin: "24AAAFO1234F1Z8" },
      { state: "Karnataka (29)", gstin: "29AAAFO1234F1Z2" },
    ],
    books: { software: "TallyPrime 4.1", lastSynced: "Today, 18:30" },
    retainerMonthly: 45000,
    recoveryPct: 82,
    activeTasksCount: 5,
    overdueTasksCount: 2,
  },
  {
    id: "shreeji",
    name: "Shreeji Constructions Pvt Ltd",
    code: "C-02",
    entityType: "Private Limited",
    industry: "EPC & Infrastructure",
    turnover: "₹14.2 Cr",
    tier: 1,
    health: "healthy",
    pan: "AABCS9821K",
    tan: "PUNS09182D",
    udyam: "UDYAM-MH-02-0081729",
    gstins: [
      { state: "Maharashtra (27)", gstin: "27AABCS9821K1Z2" },
      { state: "Madhya Pradesh (23)", gstin: "23AABCS9821K1Z4" },
    ],
    books: { software: "Zoho Books Cloud", lastSynced: "Yesterday, 14:15" },
    retainerMonthly: 85000,
    recoveryPct: 96,
    activeTasksCount: 7,
    overdueTasksCount: 0,
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: "task-01",
    title: "GSTR-1 sales ledger matching & E-way bill validation",
    clientId: "oswal",
    clientName: "Oswal Exports",
    engagement: "GST Compliance & Scrutiny",
    status: "in-progress",
    priority: "high",
    dueDate: "11 Sep (Overdue)",
    isOverdue: true,
    estHours: 4.0,
    loggedHours: 2.0,
    assignees: [
      { id: "priya", name: "Priya Agarwal", initials: "PA", role: "Sr. Accountant", avatarColor: "bg-purple-600" },
      { id: "rajesh", name: "Rajesh Sharma", initials: "RS", role: "Partner", avatarColor: "bg-blue-600" },
    ],
    reviewer: "Rajesh Sharma (Partner)",
    statutoryTag: "GSTR-1 · 11 Sep",
    docsRequired: 5,
    docsReceived: 5,
  },
  {
    id: "task-02",
    title: "DSC Passcode Token Expiry & Custody Management",
    clientId: "oswal",
    clientName: "Oswal Exports",
    engagement: "Statutory Governance",
    status: "internal-review",
    priority: "urgent",
    dueDate: "Today, 17:00",
    isOverdue: true,
    estHours: 2.0,
    loggedHours: 1.5,
    assignees: [
      { id: "rajesh", name: "Rajesh Sharma", initials: "RS", role: "Partner", avatarColor: "bg-blue-600" },
    ],
    reviewer: "Rajesh Sharma (Partner)",
    statutoryTag: "eMudhra Vault",
    docsRequired: 2,
    docsReceived: 2,
  },
  {
    id: "task-03",
    title: "GSTR-3B Monthly Return Filing (August 2026)",
    clientId: "oswal",
    clientName: "Oswal Exports",
    engagement: "GST Compliance & Scrutiny",
    status: "in-progress",
    priority: "high",
    dueDate: "20 Sep 2026",
    estHours: 4.0,
    loggedHours: 2.5,
    assignees: [
      { id: "priya", name: "Priya Agarwal", initials: "PA", role: "Sr. Accountant", avatarColor: "bg-purple-600" },
      { id: "aditya", name: "Aditya Sharma", initials: "AS", role: "Associate", avatarColor: "bg-emerald-600" },
    ],
    reviewer: "Rajesh Sharma (Partner)",
    statutoryTag: "GSTR-3B · 20 Sep",
    docsRequired: 5,
    docsReceived: 5,
  },
  {
    id: "task-04",
    title: "Match GSTR-2B - resolve ₹3.2L supplier ITC mismatch",
    clientId: "oswal",
    clientName: "Oswal Exports",
    engagement: "GST Compliance & Scrutiny",
    status: "blocked",
    priority: "urgent",
    dueDate: "18 Sep 2026",
    estHours: 5.0,
    loggedHours: 3.0,
    assignees: [
      { id: "aditya", name: "Aditya Sharma", initials: "AS", role: "Associate", avatarColor: "bg-emerald-600" },
      { id: "rajesh", name: "Rajesh Sharma", initials: "RS", role: "Partner", avatarColor: "bg-blue-600" },
    ],
    reviewer: "Rajesh Sharma (Partner)",
    statutoryTag: "ITC Rule 37A",
    notes: "Partner ruling required on ₹3.2L supplier ITC mismatch",
    docsRequired: 4,
    docsReceived: 2,
  },
  {
    id: "task-05",
    title: "Tax Audit Form 3CD Clause 44 Breakdown (MSME & GST)",
    clientId: "oswal",
    clientName: "Oswal Exports",
    engagement: "Statutory Tax Audit FY 2025-26",
    status: "todo",
    priority: "normal",
    dueDate: "30 Sep 2026",
    estHours: 6.0,
    loggedHours: 0,
    assignees: [
      { id: "vikram", name: "Vikram Meena", initials: "VM", role: "Audit Lead", avatarColor: "bg-amber-600" },
    ],
    reviewer: "Rajesh Sharma (Partner)",
    statutoryTag: "Sec 44AB",
    docsRequired: 8,
    docsReceived: 7,
  },
  {
    id: "task-06",
    title: "Advance Tax Computation - Q2 FY 2026-27 Installment",
    clientId: "shreeji",
    clientName: "Shreeji Constructions Pvt Ltd",
    engagement: "Direct Tax & Corporate Advisory",
    status: "internal-review",
    priority: "high",
    dueDate: "15 Sep 2026",
    estHours: 4.5,
    loggedHours: 3.5,
    assignees: [
      { id: "priya", name: "Priya Agarwal", initials: "PA", role: "Sr. Accountant", avatarColor: "bg-purple-600" },
    ],
    reviewer: "Rajesh Sharma (Partner)",
    statutoryTag: "Adv Tax Q2",
    docsRequired: 3,
    docsReceived: 3,
  },
  {
    id: "task-07",
    title: "RERA Escrow Account Quarterly Reconciliation",
    clientId: "shreeji",
    clientName: "Shreeji Constructions Pvt Ltd",
    engagement: "Statutory & RERA Assurance",
    status: "client-approval",
    priority: "normal",
    dueDate: "22 Sep 2026",
    estHours: 5.0,
    loggedHours: 4.5,
    assignees: [
      { id: "vikram", name: "Vikram Meena", initials: "VM", role: "Audit Lead", avatarColor: "bg-amber-600" },
    ],
    reviewer: "Rajesh Sharma (Partner)",
    statutoryTag: "RERA Cert",
    docsRequired: 6,
    docsReceived: 6,
  },
  {
    id: "task-08",
    title: "PF & ESIC Monthly Remittance Filing (Challan ECR)",
    clientId: "shreeji",
    clientName: "Shreeji Constructions Pvt Ltd",
    engagement: "Payroll & Labour Law",
    status: "filed",
    priority: "normal",
    dueDate: "15 Sep 2026",
    estHours: 2.0,
    loggedHours: 2.0,
    assignees: [
      { id: "aditya", name: "Aditya Sharma", initials: "AS", role: "Associate", avatarColor: "bg-emerald-600" },
    ],
    reviewer: "Rajesh Sharma (Partner)",
    statutoryTag: "EPFO ECR",
    docsRequired: 1,
    docsReceived: 1,
  },
];

export const TEAM_MEMBERS: TeamMemberCapacity[] = [
  {
    id: "priya",
    name: "Priya Agarwal",
    initials: "PA",
    role: "Senior Accountant",
    allocatedHours: 58,
    capacityHours: 40,
    utilizationPct: 147,
    status: "overloaded",
    activeTasks: 14,
    color: "#6366F1",
  },
  {
    id: "rajesh",
    name: "Rajesh Sharma",
    initials: "RS",
    role: "Partner (Sign-off)",
    allocatedHours: 45,
    capacityHours: 35,
    utilizationPct: 129,
    status: "overloaded",
    activeTasks: 23,
    color: "#2563EB",
  },
  {
    id: "neha",
    name: "Neha Jain",
    initials: "NJ",
    role: "Client Engagement Mgr",
    allocatedHours: 46,
    capacityHours: 40,
    utilizationPct: 116,
    status: "overloaded",
    activeTasks: 9,
    color: "#EC4899",
  },
  {
    id: "vikram",
    name: "Vikram Meena",
    initials: "VM",
    role: "Audit Lead",
    allocatedHours: 39,
    capacityHours: 40,
    utilizationPct: 98,
    status: "optimal",
    activeTasks: 8,
    color: "#0D9488",
  },
  {
    id: "aditya",
    name: "Aditya Sharma",
    initials: "AS",
    role: "Associate",
    allocatedHours: 36,
    capacityHours: 40,
    utilizationPct: 91,
    status: "optimal",
    activeTasks: 6,
    color: "#10B981",
  },
];
